### 1. 랜덤함수와 seed값 설정하기

#### seed값 설정하기

여러 명이서 작업할 때 랜점한 값이 나오되. 동일한 랜덤한 값이 나오도록 지정하는 방법   
보통은 한 번만 지정하면 계속해서 사용할 수 있다.

seed값을 설정하기 않을 때는 랜덤한 난수 값이 어떤 기준으로 만들어질까?  
컴퓨터 내부적 시간을 기준으로 그때마다 다른 값을 도출하도록 알고리즘이 구현되어져 있다.  
시드값은 seed()함수 안에 숫자를 넣음으로써 수동으로 값을 만들어내는 알고리즘...  

시드값은 0 혹은 양의 정수만 사용 가능  
seed(0)  
seed(100)  
seed(23)  
이때 seed()안에 넣는 정수가 동일하면 동일한 알고리즘이 돌기 때문에 같은 수의 난수를 지정받을수 있다.

In [35]:
np.random.seed(0)

In [11]:
import numpy as np

arr1 = np.random.randn(4,4)
arr1

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349],
       [-0.58359505,  0.81684707,  0.67272081, -0.10441114]])

In [12]:
arr2 = np.arange(1,10)
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# reshape 함수를 사용할 때는 인자값을 잘 선택해야 한다.
# arr3 = arr2.reshape(2,4) # error
arr3 = arr2.reshape(3,3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr4 = np.random.randint(10,20,16).reshape(4,4)
print(arr4)

arr4_1 = np.random.randint(10, size = 9)
print(arr4_1)

[[15 10 13 13]
 [17 19 13 15]
 [12 14 17 16]
 [18 18 11 16]]


### 2. 인덱싱, 슬라이싱

In [20]:
narray = np.arange(5)
narray

array([0, 1, 2, 3, 4])

In [27]:
# 1. 인덱싱과 슬라이싱으로 값 추출하기
'''
narray[-1] : 인덱스에 음수가 붙으면 뒤에서 n번째로 이해하기
'''
print(narray[1], narray[-1]) 
print(narray[1:]) # 두번째 요소부터 끝까지
print(narray[:]) # 모든 요소 추출
print(narray[2:4]) # 마지막 인덱스는 포함하지 않는다.

1 4
[1 2 3 4]
[0 1 2 3 4]
[2 3]


In [37]:
arr4

array([[15, 10, 13, 13],
       [17, 19, 13, 15],
       [12, 14, 17, 16],
       [18, 18, 11, 16]])

In [51]:
# 1) arr4의 첫번째 줄의 세번째 값(13)
print(arr4[0][3])
print(arr4[0,3])

# 2) arr4의 두번째 줄 [17,19,13,15]
print(arr4[1,:])
print(arr4[1,0:])
print(arr4[1:2,:]) # 2차원 출력
print(arr4[1])

# 3) arr4 전체 행에 대해서 4번째 열을 가지고 오려면?
print(arr4[:, 3])
print(arr4[0:4, 3:4]) # 2차원
print(arr4[:, 3:]) # 2차원

# 4) arr4 전체 행에 대해서 1,2번째 열을 가지고 오려면?
print(arr4[:,1:3])

13
13
[17 19 13 15]
[17 19 13 15]
[[17 19 13 15]]
[17 19 13 15]
[13 15 16 16]
[[13]
 [15]
 [16]
 [16]]
[[13]
 [15]
 [16]
 [16]]
[[10 13]
 [19 13]
 [14 17]
 [18 11]]


### 3. 인덱싱과 조건 슬라이싱
- 신입 평가 시 이 부분에서 어려운 문제를 내서 걸러냄
- 열거된 배열의 값에서 논리연산자 혹은 where 함수를 사용해서 내가 원하는 값을 가져올 수 있어야 한다.

In [88]:
arr2 = np.random.randn(4,4)
print(arr2)

# 1. 논리 연산자 사용
print(arr2>0)
print(arr2[arr2 > 0])
print(arr2[arr2 < 0])

# 2. 0보다 작은 값들(음수)은 전부 다 0으로 바꿔보겠다.
arr2[arr2 < 0] = 0
arr2 # 원본이 바뀐다.

[[ 1.47734042 -0.08489011  0.42769657 -0.30427959]
 [ 0.20462457 -0.08333816  1.82893094 -0.24417948]
 [ 0.47526083 -0.71421619 -1.18693587  0.60889084]
 [ 0.50422279 -0.51399562  0.81847537  1.15660011]]
[[ True False  True False]
 [ True False  True False]
 [ True False False  True]
 [ True False  True  True]]
[1.47734042 0.42769657 0.20462457 1.82893094 0.47526083 0.60889084
 0.50422279 0.81847537 1.15660011]
[-0.08489011 -0.30427959 -0.08333816 -0.24417948 -0.71421619 -1.18693587
 -0.51399562]


array([[1.47734042, 0.        , 0.42769657, 0.        ],
       [0.20462457, 0.        , 1.82893094, 0.        ],
       [0.47526083, 0.        , 0.        , 0.60889084],
       [0.50422279, 0.        , 0.81847537, 1.15660011]])

In [66]:
# 3. where 함수를 사용
arr2_w = np.where(arr2 > 0, arr2, -1)
arr2_w

array([[ 0.06000009,  0.51379384, -1.        , -1.        ],
       [ 0.35476966, -1.        ,  0.47174338, -1.        ],
       [-1.        ,  0.25278526, -1.        , -1.        ],
       [ 0.79976165,  2.2141412 ,  0.43887142,  0.6382597 ]])

In [76]:
### 중요 --> 많이 틀리는 이유
exama = np.array([[1,2],[3,4],[5,6]])
exama

# exama[exama[:] > 2]
result = (exama>2)
result

exama[result]

array([3, 4, 5, 6])

### 4. Numpy 통계함수

- sum() : 합
- min() : 최소값
- max() : 최대값
- mena() : 평균값
- argmax() : 가장 큰 값을 갖는 인덱스
- argmin() : 가장 작은 값을 갖는 인덱스
- cumsum() : 누적합


In [77]:
arr4

array([[15, 10, 13, 13],
       [17, 19, 13, 15],
       [12, 14, 17, 16],
       [18, 18, 11, 16]])

In [86]:
print(np.sum(arr4))
print(np.sum(arr4, axis = 1)) # 열의 합
print(np.sum(arr4, axis = 0)) # 행의 합
print(np.argmax(arr4, axis = 0)) # asix = 0이므로 위에서 아래로 행을 판별
print(np.argmax(arr4, axis = 1)) # asix = 1이므로 왼쪽에서 오른쪽으로 열을 판별
print(np.cumsum(arr4))

237
[51 64 59 63]
[62 61 54 60]
[3 1 2 2]
[0 1 2 0]
[ 15  25  38  51  68  87 100 115 127 141 158 174 192 210 221 237]
