# Numpy

Numpy는 Numeric Python의 줄임말  
수학 분양 관련된 통계나 연산 작업 시 사용하는 라이브러리  
과학 계산 컴퓨팅와 데이터 분석에 필요한 기본적인 패키지  

파이썬의 리스트와 거의 흡사  
리스트보다 빠르고 메모리 효율성이 높아서 성능적인 측면에서 훨씬 우위를 차지한다.  

Numpy 사용  
- 1) 해당 모듈을 import  
- 2) array() 함수 사용  
- 3) random 모듈 사용  

In [1]:
import numpy as np

### 1. Numpy 배열과 리스트를 비교

####  numpy의 array() 함수 사용

In [15]:
# 1. array() 함수 사용
myList = [4,5,6,7] # 리스트
myArr = np.array(myList) # numpy 배열

print(myList)
print(myArr)

'''
ndarray
다차원 행렬 구조를 지원하는 Numpy의 핵심 클래스
Numpy 배열은 ndarray클래스 타입으로 지원된다.
list - - - python
ndarray - - - Numpy

1차원 구조 --> 벡터
2차원 구조 --> 메트릭트

'''
print(type(myList))
print(type(myArr)) # ndarray 기억하기

'''
myListSlice : 카멜 기법
myList_slice : 케밥 기법
'''
'''
인덱싱 -> 몇 번째를 가리키는 것
슬라이싱 -> 시작 인덱스 : 끝 인덱스 ( 시작 ~ 끝-1 까지 자르겠다.)
'''
myList_slice = myList[1:3]
print(myList_slice)

myArr_slice = myArr[1:3]
print(myArr_slice)

myList_slice[0] = -5
myArr_slice[0] = -5

print(myList_slice)
print(myArr_slice)

# 리스트와 ndarray의 차이점을 정리
print(myList) # 원본 안바뀐다. => 카피해서 새로운걸 만든다.
print(myArr) # 원본 바뀐다. => 원본을 바로 바꿔 버린다...메모리 효율성이 뛰어나다.

[4, 5, 6, 7]
[4 5 6 7]
<class 'list'>
<class 'numpy.ndarray'>
[5, 6]
[5 6]
[-5, 6]
[-5  6]
[4, 5, 6, 7]
[ 4 -5  6  7]


#### numpy의 random 모듈 사용

In [42]:
a = np.random.rand(3)
print(a)
print(type(a))

# np.random.rand? # ? 를 붙이면 해당 메소드의 설명 확인 가능
# 2차원일때 [[]]와 같이 []안에 []가 있음. 중요!!

b = np.random.randint(1,10,5) # 1~(10-1)까지의 정수 5개
print(b)
print(type(b))

c = np.random.randn(10) # 가우시안 표준분포
print(c)
print(type(c))

[0.15802793 0.67571097 0.65626651]
<class 'numpy.ndarray'>
[4 2 8 3 9]
<class 'numpy.ndarray'>
[-0.66959534 -0.24021649  1.30178472 -0.56485956  0.1427052  -1.41078527
 -0.13585211 -0.05790501  0.15519523 -1.25378682]
<class 'numpy.ndarray'>


####  2. Numpy배열의 초기화

- zeros()
- ones()
- arange()

In [51]:
# 1. zeros()

az = np.zeros(10) # 인자값은 size
print(az) # 실수이기 때문에 0. 으로 표기

# 2. onese() : 1값으로 이뤄진 크기가 n인 배열
ao = np.ones(10)
print(ao)

# 3. eye() : n by n 단위의 배열을 생성
ae = np.eye(3)
print(ae)

# 4. arange()
print(np.arange(3)) 
print(np.arange(3, 7)) 
print(np.arange(3, 10, 2)) 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 1 2]
[3 4 5 6]
[3 5 7 9]


ndarray를 생성할 때   
0, 1로 값을 채우는 함수가 제공되어져 있다...zeros(), ones()  
2, 3, ?..등의 값으로 초기화 하고 싶다.  
방법은?  

In [68]:
# np함수에 특정한 값에 대한 연산이 가능하다.
# 결론은 모든 특정한 값으로 초기화 가능하다.
am = np.ones(10) + 3
print(am)

print(np.eye(3))

# full() 모든 배열의 초기화는 어느정도 가능하다.
af = np.full((5,5), -11)
print(af)

[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]]


#### 3. 리스트와 np 배열의 차이점

리스트와 np 배열의 차이점 정리

리스트는 서로 다른 타입의 값들 저장이 가능한 반면에  
np 배열은 하나의 자료형만 저장할 수 있다.

In [71]:
L = [1,2,3,'4',5]
number = [1,2,3, 4.0, 5]

print(L)
print(type(L))
print(number)
print(type(number))

[1, 2, 3, '4', 5]
<class 'list'>
[1, 2, 3, 4.0, 5]
<class 'list'>


In [75]:
# 리스트가 np 배열로 초기화될 때 데이터 타입이 큰 것을 기준으로 초기화됨.
narray_1 = np.array(L)
print(narray_1)

narray_2 = np.array(number)
print(narray_2)

# 값의 타입을 명시해서 저장할 수 도 있다. 이때 dtype 속성을 사용한다.
# narray_3 = np.array([1,2,3,4], dtype = 'float') # 같은 자료형만 저장...
narray_3 = np.array([1,2,3,4], dtype = np.float32)
print(narray_3)

['1' '2' '3' '4' '5']
[1. 2. 3. 4. 5.]
[1. 2. 3. 4.]


#### 4. Numpy 배열의 속성 혹은 함수

- ndim : 배열의 차원 수 or 배열의 축 수
- shape : 배열 각 차원의 크기를 튜플 형태로 표현. n행과 m열의 행렬의 경우 (n,m) 형태의 튜플로 나타냄
- reshape : 행,열 재정의
- size    
- type : 배열 객체의 type
- dtype : 배열의 원소의 종류. 기본적으로 넘파이의 원소들은 모두 같은 데이터 타입을 가지고 있다.

In [88]:
arr1 = np.array([[1.0,2,3], [4,5,6]], dtype = np.int32)
print(arr1)

# np의 함수를 이용해서 
# 데이터의 타입, 차원, 몇행몇열, 테이터가 총 몇개인지, ...출력
print('데이터 타입 : ',type(arr1)) # 객체 type
print('차원 : ',np.ndim(arr1))
print('행열 : ',np.shape(arr1))
print('개수 : ',np.size(arr1))
print('\n','*'*30)

# 속성으로 나타낼 때
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)
print(arr1.dtype) # 배열 안 값의 type
# print(arr1.type) # type은 함수지 속성은 아님
print('\n','*'*30)

# arr1 배열의 원소값의 타입을 한번에 다른 타입으로 바꿀 수 있다. astype()
# 정수 --> 실수
arr1_1 = arr1.astype(np.float64)
print(arr1_1)
print(type(arr1_1))
print('\n','*'*30)

arr2 = np.arange(32).reshape(8,4)
print(arr2)

[[1 2 3]
 [4 5 6]]
데이터 타입 :  <class 'numpy.ndarray'>
차원 :  2
행열 :  (2, 3)
개수 :  6

 ******************************
2
(2, 3)
6
int32

 ******************************
[[1. 2. 3.]
 [4. 5. 6.]]
<class 'numpy.ndarray'>

 ******************************
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
